title: Summer seminar
description: >
 The University of Michigan's summer seminar 
 in economics.
baseurl: "/UMSumSem"
url: "mzabek.github.io/UMSumSem/"
paginate:	3 # The number of posts to show per page on your homepage
name: "Mike Zabek and Ariel Bender"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
